title: Apurv Chudasama | Portfolio & Blog
description: AI Engineer & Data Scientist specializing in Machine Learning, Computer Vision, and Deep Learning.
url: "https://apurv090405.github.io"
baseurl: "/Apurv-Chudasama"

# Blog Settings
future: true
show_drafts: true

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      permalink: "/blog/:year/:month/:day/:title/"
